# name: Deploy to WordPress.org

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  deploy-plugin:
    name: Deploy Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: logichat
          VERSION: 1.0.2
